eprime_task_cols <- list(
  "n-back" = c("Running",
               "Pic",
               "CR",
               "StimTest.ACC",
               "StimTest.RT",
               "StimTest.RESP",
               "StimTest.CRESP",
               "Stim.ACC",
               "Stim.RT",
               "Stim.RESP",
               "Stim.CRESP"),
  "Attention" = c("Running",
                  "WarningType",
                  "FlankerType",
                  "TargetType1",
                  "TargerDirection",
                  "Sample",
                  "PracSlideTarget.ACC",
                  "PracSlideTarget.RT",
                  "PracSlideTarget.RESP",
                  "PracSlideTarget.CRESP",
                  "TargetType",
                  "TargetDirection",
                  "SlideTarget.ACC",
                  "SlideTarget.RT",
                  "SlideTarget.RESP",
                  "SlideTarget.CRESP"),
  "Antisaccade" = c("Running",
                    "Arrow",
                    "CR",
                    "Eprime.LevelName",
                    "Sample",
                    "Target1.ACC",
                    "Target1.RT",
                    "Target1.RESP",
                    "Target1.CRESP",
                    "TrialList",
                    "Target.ACC",
                    "Target.RT",
                    "Target.RESP",
                    "Target.CRESP")
)
usethis::use_data(eprime_task_cols, overwrite = TRUE, internal = TRUE)
